app:
  name: "BitcoinInfo"
  version: "0.0.1"
  debug: true
  port: 8080

database:
  host: "localhost"
  port: 5432
  user: "postgres"
  password: "postgres"
  name: "bitcoininfo"

api:
  endpoint: https://blockchain.info
  confirmations: 6
  retry_attempts: 3
  timeout: 5
